import type { LoanApplicationSeed } from "@/lib/apis/seeder-types"
import type { LoanFormData } from "@/lib/loan-form-types"

export function fillDemoData(seed: LoanApplicationSeed): LoanFormData {
  const nameParts = seed.borrowerName.trim().split(" ")
  const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : nameParts[0]
  const firstName = nameParts.length > 1 ? nameParts.slice(0, -1).join(" ") : ""

  return {
    customerInfo: {
      firstName,
      lastName,
      dateOfBirth: "",
      gender: seed.gender,
      nationalId: "",
      nationalIdIssueDate: "",
      nationalIdIssuePlace: "",
      email: "",
      phone: "",
      landlinePhone: "",
      maritalStatus: seed.maritalStatus,
      bidvRelationship: "",
    },
    customerIncome: {
      employmentStatus: seed.employmentType,
      employerName: seed.employerName,
      jobTitle: seed.jobTitle,
      employerAddress: "",
      employerPhone: "",
      yearsEmployed: (seed.employmentDurationMonths / 12).toFixed(1),
      monthlyIncome: String(seed.monthlyIncome),
      businessIncome: "",
      rentalIncome: "",
      additionalIncome: String(seed.otherIncome),
      incomeSource: "",
      livingExpenses: "",
      installmentExpenses: String(seed.monthlyDebtPayments),
      realEstateAssets: "",
      movableAssets: "",
      depositAssets: "",
    },
    customerRelationship: {
      coborrowerName: "",
      coborrowerDateOfBirth: "",
      coborrowerGender: "",
      coborrowerIdNumber: "",
      coborrowerIdIssueDate: "",
      coborrowerIdIssuePlace: "",
      coborrowerCurrentAddress: "",
      coborrowerMobilePhone: "",
      coborrowerMonthlyIncome: "",
      referenceName1: "",
      referencePhone1: "",
      referenceRelation1: "",
      referenceAddress1: "",
      referenceName2: "",
      referencePhone2: "",
      referenceRelation2: "",
      existingCustomer: "",
      accountNumber: "",
    },
    customerLocation: {
      permanentAddress: "",
      addressLine1: "",
      addressLine2: "",
      city: "",
      state: "",
      postalCode: "",
      country: "",
      residenceType: "",
      yearsAtAddress: "",
    },
    loanInfo: {
      loanType: seed.loanProductCode,
      loanMethod: "",
      loanAmount: String(seed.requestedAmount),
      loanTerm: String(seed.requestedTenureMonths),
      loanPurpose: seed.purpose,
      repaymentSource: "",
      principalRepaymentPeriod: "",
      interestRepaymentPeriod: "",
      principalRepaymentMethod: "",
      repaymentMethod: "",
      repaymentAccountNumber: "",
      collateralType: "",
      collateralValue: "",
      collateralAddress: "",
      collateralOwnerType: "",
      insurancePackage: "",
      insurancePaymentMethod: "",
    },
  }
}
