import type { LoanApplicationSeed } from "@/lib/apis/seeder-types"
import type { LoanFormData } from "@/lib/loan-form-types"

export function fillDemoData(seed: LoanApplicationSeed): LoanFormData {
  const nameParts = seed.borrowerName.trim().split(" ")
  const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : nameParts[0]
  const firstName = nameParts.length > 1 ? nameParts.slice(0, -1).join(" ") : ""

  return {
    customerInfo: {
      firstName,
      lastName,
      dateOfBirth: seed.dateOfBirth ?? "",
      gender: seed.gender,
      nationalId: seed.nationalId ?? "",
      nationalIdIssueDate: seed.nationalIdIssueDate ?? "",
      nationalIdIssuePlace: seed.nationalIdIssuePlace ?? "",
      email: seed.email ?? "",
      phone: seed.phone ?? "",
      landlinePhone: "",
      maritalStatus: seed.maritalStatus,
      hasRelationship: seed.hasRelationship ?? "",
    },
    customerIncome: {
      employmentStatus: seed.employmentType,
      employerName: seed.employerName,
      employerAddress: seed.employerAddress ?? "",
      employerPhone: seed.employerPhone ?? "",
      jobTitle: seed.jobTitle,
      yearsEmployed: (seed.employmentDurationMonths / 12).toFixed(1),
      monthlyIncome: String(seed.monthlyIncome),
      businessIncome: seed.businessIncome ?? "",
      rentalIncome: seed.rentalIncome ?? "",
      additionalIncome: seed.otherIncome > 0 ? String(seed.otherIncome) : "",
      incomeSource: seed.incomeSource ?? "",
      livingExpenses: seed.livingExpenses ?? "",
      installmentExpenses: String(seed.monthlyDebtPayments),
      realEstateAssets: seed.realEstateAssets ?? "",
      movableAssets: seed.movableAssets ?? "",
      depositAssets: seed.depositAssets ?? "",
    },
    customerRelationship: {
      coborrowerName: "",
      coborrowerDateOfBirth: "",
      coborrowerGender: "",
      coborrowerIdNumber: "",
      coborrowerIdIssueDate: "",
      coborrowerIdIssuePlace: "",
      coborrowerCurrentAddress: "",
      coborrowerMobilePhone: "",
      coborrowerMonthlyIncome: "",
      referenceName1: seed.referenceName1 ?? "",
      referencePhone1: seed.referencePhone1 ?? "",
      referenceRelation1: seed.referenceRelation1 ?? "",
      referenceAddress1: seed.referenceAddress1 ?? "",
      referenceName2: "",
      referencePhone2: "",
      referenceRelation2: "",
      existingCustomer: seed.existingCustomer ?? "",
      accountNumber: seed.accountNumber ?? "",
    },
    customerLocation: {
      permanentAddress: seed.permanentAddress ?? "",
      addressLine1: seed.addressLine1 ?? "",
      addressLine2: seed.addressLine2 ?? "",
      city: seed.city ?? "",
      state: seed.state ?? "",
      postalCode: seed.postalCode ?? "",
      country: seed.country ?? "vn",
      residenceType: seed.residenceType ?? "",
      yearsAtAddress: seed.yearsAtAddress ?? "",
    },
    loanInfo: {
      loanType: seed.loanType ?? "",
      loanMethod: seed.loanMethod ?? "",
      loanAmount: String(seed.requestedAmount),
      loanTerm: String(seed.requestedTenureMonths),
      loanPurpose: seed.purpose,
      repaymentSource: seed.repaymentSource ?? "",
      principalRepaymentPeriod: seed.principalRepaymentPeriod ?? "",
      interestRepaymentPeriod: seed.interestRepaymentPeriod ?? "",
      principalRepaymentMethod: seed.principalRepaymentMethod ?? "",
      repaymentMethod: seed.repaymentMethod ?? "",
      repaymentAccountNumber: "",
      collateralType: seed.collateralType ?? "",
      collateralValue: seed.collateralValue ?? (seed.estimatedCollateralValue > 0 ? String(seed.estimatedCollateralValue) : ""),
      collateralAddress: seed.collateralAddress ?? "",
      collateralOwnerType: seed.collateralOwnerType ?? "",
      insurancePackage: seed.insurancePackage ?? "",
      insurancePaymentMethod: seed.insurancePaymentMethod ?? "",
    },
  }
}
