import { Staff } from './staff-types';

export const mockStaff: Staff[] = [
  {
    id: 'staff_001',
    name: 'John Smith',
    email: 'john.smith@loanbank.com',
    phone: '+1-555-0101',
    role: 'loan_officer',
    department: 'Personal Loans',
    dateJoined: new Date('2022-06-15'),
    status: 'active',
    assignedLoans: ['LOAN-001', 'LOAN-003', 'LOAN-005'],
  },
  {
    id: 'staff_002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@loanbank.com',
    phone: '+1-555-0102',
    role: 'processor',
    department: 'Mortgages',
    dateJoined: new Date('2021-03-22'),
    status: 'active',
    assignedLoans: ['LOAN-002', 'LOAN-006'],
  },
  {
    id: 'staff_003',
    name: 'Michael Chen',
    email: 'michael.chen@loanbank.com',
    phone: '+1-555-0103',
    role: 'reviewer',
    department: 'Personal Loans',
    dateJoined: new Date('2020-11-10'),
    status: 'active',
    assignedLoans: ['LOAN-004'],
  },
  {
    id: 'staff_004',
    name: 'Emma Davis',
    email: 'emma.davis@loanbank.com',
    phone: '+1-555-0104',
    role: 'loan_officer',
    department: 'Business Loans',
    dateJoined: new Date('2023-01-05'),
    status: 'active',
    assignedLoans: [],
  },
  {
    id: 'staff_005',
    name: 'Robert Williams',
    email: 'robert.williams@loanbank.com',
    phone: '+1-555-0105',
    role: 'manager',
    department: 'Personal Loans',
    dateJoined: new Date('2019-08-30'),
    status: 'active',
    assignedLoans: [],
  },
  {
    id: 'staff_006',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@loanbank.com',
    phone: '+1-555-0106',
    role: 'processor',
    department: 'Auto Loans',
    dateJoined: new Date('2022-09-12'),
    status: 'inactive',
    assignedLoans: [],
  },
];