export interface LoanApplicationSeed {
  applicationNumber: string
  borrowerName: string
  age: number
  gender: string
  maritalStatus: string
  loanProductCode: string
  requestedAmount: number
  requestedTenureMonths: number
  purpose: string
  channel: string
  employmentType: string
  employerName: string
  industry: string
  jobTitle: string
  employmentDurationMonths: number
  contractType?: string
  monthlyIncome: number
  otherIncome: number
  totalMonthlyIncome: number
  monthlyDebtPayments: number
  dtiRatio: number
  cicScore: number
  creditHistoryYears: number
  closedLoansCount: number
  activeLoansCount: number
  latePaymentCount: number
  maxDaysLate: number
  hasDefaultHistory: boolean
  onTimePaymentPercentage: number
  totalCreditLimit: number
  totalDebtOutstanding: number
  creditUtilizationRatio: number
  inquiriesLast6Months: number
  hasCollateral: boolean
  collateralDescription?: string
  estimatedCollateralValue: number
  hasGuarantor: boolean
  numberOfGuarantors: number
  autoScoreTotal: number
  autoScoreGrade: string
  riskScoreTotal: number
  riskRating: string
  status: string
  underwritingDecision: string
  decisionReason: string
  submittedAt: string
  reviewedAt?: string
  // form fields — customerInfo
  dateOfBirth?: string
  nationalId?: string
  nationalIdIssueDate?: string
  nationalIdIssuePlace?: string
  email?: string
  phone?: string
  bidvRelationship?: string
  // form fields — customerIncome
  employerAddress?: string
  employerPhone?: string
  businessIncome?: string
  rentalIncome?: string
  incomeSource?: string
  livingExpenses?: string
  realEstateAssets?: string
  movableAssets?: string
  depositAssets?: string
  // form fields — customerRelationship
  referenceName1?: string
  referencePhone1?: string
  referenceRelation1?: string
  referenceAddress1?: string
  existingCustomer?: string
  accountNumber?: string
  // form fields — customerLocation
  permanentAddress?: string
  addressLine1?: string
  addressLine2?: string
  city?: string
  state?: string
  postalCode?: string
  country?: string
  residenceType?: string
  yearsAtAddress?: string
  // form fields — loanInfo
  loanType?: string
  loanMethod?: string
  repaymentSource?: string
  principalRepaymentPeriod?: string
  interestRepaymentPeriod?: string
  principalRepaymentMethod?: string
  repaymentMethod?: string
  collateralType?: string
  collateralValue?: string
  collateralAddress?: string
  collateralOwnerType?: string
  insurancePackage?: string
  insurancePaymentMethod?: string
}
