export interface LoanApplicationSeed {
  applicationNumber: string
  borrowerName: string
  age: number
  gender: string
  maritalStatus: string
  loanProductCode: string
  requestedAmount: number
  requestedTenureMonths: number
  purpose: string
  channel: string
  employmentType: string
  employerName: string
  industry: string
  jobTitle: string
  employmentDurationMonths: number
  contractType?: string
  monthlyIncome: number
  otherIncome: number
  totalMonthlyIncome: number
  monthlyDebtPayments: number
  dtiRatio: number
  cicScore: number
  creditHistoryYears: number
  closedLoansCount: number
  activeLoansCount: number
  latePaymentCount: number
  maxDaysLate: number
  hasDefaultHistory: boolean
  onTimePaymentPercentage: number
  totalCreditLimit: number
  totalDebtOutstanding: number
  creditUtilizationRatio: number
  inquiriesLast6Months: number
  hasCollateral: boolean
  collateralDescription?: string
  estimatedCollateralValue: number
  hasGuarantor: boolean
  numberOfGuarantors: number
  autoScoreTotal: number
  autoScoreGrade: string
  riskScoreTotal: number
  riskRating: string
  status: string
  underwritingDecision: string
  decisionReason: string
  submittedAt: string
  reviewedAt?: string
}
